// frontend/src/app/pages/questao-form/questao-form.component.ts
import { Component, OnInit, Input, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { QuestaoService } from '../../services/questao.service';
import { Dificuldade } from '../../models/questao.model';
import { KatexDirective } from '../../directives/katex.directive';

@Component({
  selector: 'app-questao-form',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, KatexDirective],
  templateUrl: './questao-form.component.html',
  styleUrl: './questao-form.component.css'
})
export class QuestaoFormComponent implements OnInit {
  @Input() id?: string;

  private readonly questaoService = inject(QuestaoService);
  private readonly router = inject(Router);

  // Form Model
  public titulo = signal<string>('');
  public enunciado = signal<string>('');
  public materia = signal<string>('');
  public assunto = signal<string>('');
  public dificuldade = signal<number>(0);
  public fonte = signal<string>('');
  public trechoCodigo = signal<string>('');
  public linguagemCodigo = signal<string>('');
  public imagemUrl = signal<string>('');

  // Estados de IA e Upload
  public promptIA = signal<string>('');
  public gerandoIA = signal<boolean>(false);
  public enviandoImagem = signal<boolean>(false);
  public salvando = signal<boolean>(false);
  public erro = signal<string>('');

  ngOnInit(): void {
    if (this.id) {
      this.carregarParaEdicao(this.id);
    }
  }

  private carregarParaEdicao(id: string): void {
    this.questaoService.buscarPorId(id).subscribe({
      next: (q) => {
        this.titulo.set(q.titulo || '');
        this.enunciado.set(q.enunciado || '');
        this.materia.set(q.materia || '');
        this.assunto.set(q.assunto || '');
        this.dificuldade.set(Number(q.dificuldade) || 0);
        this.fonte.set(q.fonte || '');
        this.trechoCodigo.set(q.trechoCodigo || '');
        this.linguagemCodigo.set(q.linguagemCodigo || '');
        this.imagemUrl.set(q.imagemUrl || '');
      },
      error: () => this.erro.set('Erro ao carregar dados da questão para edição.')
    });
  }

  public onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (!input.files || input.files.length === 0) return;

    const file = input.files[0];
    this.enviandoImagem.set(true);
    this.questaoService.uploadImagem(file).subscribe({
      next: (res) => {
        this.imagemUrl.set(res.url);
        this.enviandoImagem.set(false);
      },
      error: () => {
        alert('Erro ao fazer upload da imagem.');
        this.enviandoImagem.set(false);
      }
    });
  }

  public gerarEsbocoIA(): void {
    const prompt = (this.promptIA() || '').trim();
    if (!prompt) {
      alert('Digite uma descrição ou ideia para o Copiloto Gemini.');
      return;
    }

    this.gerandoIA.set(true);
    this.questaoService.iaSugerir(prompt, this.enunciado() || '').subscribe({
      next: (dados) => {
        if (dados) {
          if (dados.titulo) this.titulo.set(dados.titulo);
          if (dados.enunciado) this.enunciado.set(dados.enunciado);
          if (dados.materia) this.materia.set(dados.materia);
          if (dados.assunto) this.assunto.set(dados.assunto);
          if (dados.dificuldade !== undefined) this.dificuldade.set(Number(dados.dificuldade) || 0);
          if (dados.trechoCodigo) this.trechoCodigo.set(dados.trechoCodigo);
          if (dados.linguagemCodigo) this.linguagemCodigo.set(dados.linguagemCodigo);
          if (dados.fonte) this.fonte.set(dados.fonte);
        }
        this.gerandoIA.set(false);
      },
      error: () => {
        alert('Erro ao obter sugestão da IA. Verifique as credenciais da API Gemini.');
        this.gerandoIA.set(false);
      }
    });
  }

  public criarTotalIA(): void {
    const prompt = (this.promptIA() || '').trim();
    if (!prompt) {
      alert('Digite uma descrição ou ideia para o Copiloto Gemini.');
      return;
    }

    this.gerandoIA.set(true);
    this.questaoService.iaCriarTotal(prompt).subscribe({
      next: (q) => {
        this.gerandoIA.set(false);
        this.router.navigate(['/questoes', q.id]);
      },
      error: () => {
        alert('Erro ao publicar questão com IA. Verifique as credenciais da API Gemini.');
        this.gerandoIA.set(false);
      }
    });
  }

  public removerImagem(): void {
    this.imagemUrl.set('');
  }

  public salvarQuestao(): void {
    const tit = (this.titulo() || '').trim();
    const enun = (this.enunciado() || '').trim();
    const mat = (this.materia() || '').trim();

    if (!enun) {
      alert('O enunciado da questão é obrigatório.');
      return;
    }

    this.salvando.set(true);
    const payload = {
      titulo: tit || (enun.substring(0, 45) + '...'),
      enunciado: enun,
      materia: mat || 'Geral',
      assunto: (this.assunto() || '').trim() || 'Outros',
      dificuldade: Number(this.dificuldade()) || 0,
      fonte: (this.fonte() || '').trim(),
      trechoCodigo: (this.trechoCodigo() || '').trim(),
      linguagemCodigo: (this.linguagemCodigo() || '').trim(),
      imagemUrl: (this.imagemUrl() || '').trim()
    };

    if (this.id) {
      this.questaoService.atualizar(this.id, payload).subscribe({
        next: () => {
          this.salvando.set(false);
          this.router.navigate(['/questoes', this.id]);
        },
        error: () => {
          alert('Erro ao atualizar questão.');
          this.salvando.set(false);
        }
      });
    } else {
      this.questaoService.salvar(payload).subscribe({
        next: (nova) => {
          this.salvando.set(false);
          this.router.navigate(['/questoes', nova.id]);
        },
        error: () => {
          alert('Erro ao cadastrar questão.');
          this.salvando.set(false);
        }
      });
    }
  }
}

<div class="form-container">
  <div class="form-topo">
    <a routerLink="/" class="link-voltar">Voltar ao Repositório</a>
    <h1 class="page-title">{{ id ? 'Editar Questão #' + id : 'Nova Questão Técnica' }}</h1>
    <p class="page-desc">Cadastre ou edite problemas com suporte a fórmulas em KaTeX, blocos de código e diagramas.</p>
  </div>

  <!-- Copiloto Gemini IA (apenas em modo de criação) -->
  @if (!id) {
    <div class="card-copiloto">
      <div class="copiloto-header">
        <span class="copiloto-badge">Copiloto Gemini AI</span>
        <span class="copiloto-sub">Assistente de Elaboração de Questões</span>
      </div>
      <p class="copiloto-text">
        Digite sua ideia ou tema (ex: <em>"Crie uma questão de Álgebra Linear sobre autovalores com matriz 2x2"</em>) e acelere seu fluxo de trabalho:
      </p>
      <textarea
        class="input-field copiloto-textarea"
        rows="2"
        placeholder="Descreva a questão técnica que você deseja formular..."
        [ngModel]="promptIA()"
        (ngModelChange)="promptIA.set($event)"
        [disabled]="gerandoIA()"
      ></textarea>
      <div class="copiloto-acoes">
        <button
          type="button"
          class="btn btn-copiloto-esboco"
          (click)="gerarEsbocoIA()"
          [disabled]="gerandoIA()"
        >
          @if (gerandoIA()) {
            <span class="spinner-sm"></span>
            <span>Gerando com IA...</span>
          } @else {
            <span>Preencher Esboço</span>
          }
        </button>
        <button
          type="button"
          class="btn btn-copiloto-publicar"
          (click)="criarTotalIA()"
          [disabled]="gerandoIA()"
        >
          @if (gerandoIA()) {
            <span class="spinner-sm"></span>
            <span>Publicando...</span>
          } @else {
            <span>Publicar Direto</span>
          }
        </button>
      </div>
    </div>
  }

  <!-- Formulário Principal -->
  <form (ngSubmit)="salvarQuestao()" class="card-form">
    <!-- Linha 1: Título -->
    <div class="form-group">
      <label class="form-label" for="titulo">Título da Questão (Opcional)</label>
      <input
        id="titulo"
        type="text"
        class="input-field"
        placeholder="Ex: Teorema Fundamental do Cálculo em Coordenadas Polares"
        [ngModel]="titulo()"
        (ngModelChange)="titulo.set($event)"
        name="titulo"
      />
    </div>

    <!-- Linha 2: Matéria, Assunto, Dificuldade e Fonte -->
    <div class="grid-campos">
      <div class="form-group">
        <label class="form-label" for="materia">Matéria / Área *</label>
        <input
          id="materia"
          type="text"
          class="input-field"
          placeholder="Ex: Cálculo 1, Física, Java"
          [ngModel]="materia()"
          (ngModelChange)="materia.set($event)"
          name="materia"
          required
        />
      </div>

      <div class="form-group">
        <label class="form-label" for="assunto">Assunto Específico</label>
        <input
          id="assunto"
          type="text"
          class="input-field"
          placeholder="Ex: Derivadas Parciais, Polimorfismo"
          [ngModel]="assunto()"
          (ngModelChange)="assunto.set($event)"
          name="assunto"
        />
      </div>

      <div class="form-group">
        <label class="form-label" for="dificuldade">Dificuldade</label>
        <select
          id="dificuldade"
          class="input-field select-field"
          [ngModel]="dificuldade()"
          (ngModelChange)="dificuldade.set(+$event)"
          name="dificuldade"
        >
          <option [value]="0">Fácil</option>
          <option [value]="1">Médio</option>
          <option [value]="2">Difícil</option>
        </select>
      </div>

      <div class="form-group">
        <label class="form-label" for="fonte">Fonte / Exame</label>
        <input
          id="fonte"
          type="text"
          class="input-field"
          placeholder="Ex: ITA 2024, Halliday Vol. 1, ENADE"
          [ngModel]="fonte()"
          (ngModelChange)="fonte.set($event)"
          name="fonte"
        />
      </div>
    </div>

    <!-- Linha 3: Enunciado (com Preview KaTeX) -->
    <div class="form-group">
      <div class="label-com-dica">
        <label class="form-label" for="enunciado">Enunciado da Questão *</label>
        <span class="dica-katex">Fórmulas: <code>$...$</code> para inline e <code>$$...$$</code> para bloco</span>
      </div>
      <textarea
        id="enunciado"
        class="input-field enunciado-textarea"
        rows="6"
        placeholder="Digite o enunciado detalhado da questão. Você pode incluir fórmulas em LaTeX: $x^2 + y^2 = r^2$..."
        [ngModel]="enunciado()"
        (ngModelChange)="enunciado.set($event)"
        name="enunciado"
        required
      ></textarea>
    </div>

    <!-- Preview ao Vivo em KaTeX do Enunciado -->
    @if (enunciado()) {
      <div class="preview-katex-box">
        <div class="preview-header">
          <span class="preview-tag">Prévia de Renderização KaTeX</span>
        </div>
        <div class="preview-corpo" [appKatex]="enunciado()"></div>
      </div>
    }

    <!-- Linha 4: Código Técnico Opcional -->
    <div class="grid-codigo">
      <div class="form-group campo-linguagem">
        <label class="form-label" for="linguagemCodigo">Linguagem de Programação</label>
        <select
          id="linguagemCodigo"
          class="input-field select-field"
          [ngModel]="linguagemCodigo()"
          (ngModelChange)="linguagemCodigo.set($event)"
          name="linguagemCodigo"
        >
          <option value="">Nenhuma (Apenas texto)</option>
          <option value="java">Java</option>
          <option value="python">Python</option>
          <option value="javascript">JavaScript / TypeScript</option>
          <option value="cpp">C / C++</option>
          <option value="csharp">C#</option>
          <option value="sql">SQL</option>
        </select>
      </div>

      <div class="form-group campo-trecho">
        <label class="form-label" for="trechoCodigo">Trecho de Código (Opcional)</label>
        <textarea
          id="trechoCodigo"
          class="input-field font-mono"
          rows="4"
          placeholder="Cole aqui o trecho de código ou pseudocódigo relevante..."
          [ngModel]="trechoCodigo()"
          (ngModelChange)="trechoCodigo.set($event)"
          name="trechoCodigo"
        ></textarea>
      </div>
    </div>

    <!-- Linha 5: Upload de Diagrama / Imagem da Questão -->
    <div class="form-group secao-upload">
      <label class="form-label">Diagrama ou Imagem Ilustrativa (Opcional)</label>
      <div class="upload-area">
        <input
          type="file"
          id="arquivo-imagem"
          accept="image/*"
          (change)="onFileSelected($event)"
          [disabled]="enviandoImagem()"
          class="input-file"
        />
        <label for="arquivo-imagem" class="btn btn-secondary btn-escolher-arquivo">
          @if (enviandoImagem()) {
            <span class="spinner-sm"></span>
            <span>Enviando imagem...</span>
          } @else {
            <span>Selecionar Arquivo de Imagem</span>
          }
        </label>
      </div>

      @if (imagemUrl()) {
        <div class="preview-imagem-container">
          <img [src]="imagemUrl()" alt="Diagrama da questão" class="img-preview" />
          <button
            type="button"
            class="btn-remover-img"
            (click)="removerImagem()"
            title="Remover imagem"
          >
            Remover
          </button>
        </div>
      }
    </div>

    <!-- Botões Finais de Ação -->
    <div class="form-acoes">
      <a routerLink="/" class="btn btn-secondary">Cancelar</a>
      <button
        type="submit"
        class="btn btn-primary btn-salvar"
        [disabled]="salvando() || enviandoImagem() || !enunciado()"
      >
        @if (salvando()) {
          <span class="spinner-sm"></span>
          <span>Gravando...</span>
        } @else {
          <span>{{ id ? 'Salvar Alterações' : 'Publicar Questão' }}</span>
        }
      </button>
    </div>
  </form>
</div>

// frontend-react-legacy/src/pages/QuestaoForm.jsx
import { useState } from "react";
import { questaoService } from "../services/questaoService";
import { useToastContext } from "../contexts/ToastContext";
import { getMediaUrl } from "../utils/urlUtils";

function QuestaoForm({ SalvarSucesso }) {

    const { showToast } = useToastContext();
    const [novaQuestao, setNovaQuestao] = useState({
        enunciado: "",
        imagemUrl: "",
        materia: "",
        assunto: "",
        dificuldade: "0",
        fonte: "",
        trechoCodigo: "",
        linguagemCodigo: ""
    });

    const [enviandoImagem, setEnviandoImagem] = useState(false);
    const [promptIA, setPromptIA] = useState("");
    const [gerandoIA, setGerandoIA] = useState(false);

    const handleFileChange = async (e) => {
        const file = e.target.files[0];
        if (!file) return;

        setEnviandoImagem(true);
        try {
            const data = await questaoService.uploadImagem(file);
            setNovaQuestao(prev => ({ ...prev, imagemUrl: data.imageUrl }));
            showToast('Imagem enviada com sucesso!', 'success');
        } catch (err) {
            console.error("Erro ao enviar imagem:", err);
            showToast('Erro ao enviar imagem.', 'error');
        } finally {
            setEnviandoImagem(false);
        }
    };

    const handleGerarEsbocoIA = async () => {
        if (!promptIA.trim()) {
            showToast('Digite uma ideia para a IA no campo do Copiloto.', 'error');
            return;
        }
        setGerandoIA(true);
        try {
            const dadosSugeridos = await questaoService.iaSugerir(promptIA, novaQuestao.enunciado);
            setNovaQuestao({
                enunciado: dadosSugeridos.enunciado || "",
                materia: dadosSugeridos.materia || "",
                assunto: dadosSugeridos.assunto || "",
                dificuldade: String(dadosSugeridos.dificuldade ?? "0"),
                fonte: dadosSugeridos.fonte || "Gerado por Gemini",
                trechoCodigo: dadosSugeridos.trechoCodigo || "",
                linguagemCodigo: dadosSugeridos.linguagemCodigo || ""
            });
            showToast('Esboço gerado com sucesso! Revise os campos abaixo.', 'success');
        } catch (err) {
            console.error("Erro ao gerar esboço com IA:", err);
            showToast('Erro ao obter sugestão da IA. Verifique a API Key do Gemini.', 'error');
        } finally {
            setGerandoIA(false);
        }
    };

    const handleCriarTotalIA = async () => {
        if (!promptIA.trim()) {
            showToast('Digite uma ideia para a IA no campo do Copiloto.', 'error');
            return;
        }
        setGerandoIA(true);
        try {
            const questaoSalva = await questaoService.iaCriarTotal(promptIA);
            SalvarSucesso(questaoSalva);
            setPromptIA("");
            showToast('Questão gerada e publicada com sucesso!', 'success');
        } catch (err) {
            console.error("Erro ao publicar com IA:", err);
            showToast('Erro ao publicar com IA. Verifique a API Key do Gemini.', 'error');
        } finally {
            setGerandoIA(false);
        }
    };

    const handleSalvar = async (e) => {
        e.preventDefault();

        try {
            const dadosSalvos = await questaoService.salvar(novaQuestao);
            // Avisar o componente pai (App.js) que a questão foi salvo, enviar o novo objeto
            SalvarSucesso(dadosSalvos);
            // Limpar formulário para o próximo POST
            setNovaQuestao({
                enunciado: "",
                imagemUrl: "",
                materia: "",
                assunto: "",
                dificuldade: "0",
                fonte: "",
                trechoCodigo: "",
                linguagemCodigo: ""
            });
            showToast('Questão salva com sucesso!', 'success');
        } catch (err) {
            console.error("Erro ao salvar:", err);
            showToast('Erro ao conectar com o servidor. Verifique o console.', 'error');
        }
    };

    return (
        <form onSubmit={handleSalvar} className="w-full space-y-4">

            {/* Bloco Auxiliar de IA */}
            <div className="p-4 bg-slate-50 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-700/60 rounded-xl space-y-3 transition-colors">
                <label className="block text-sm font-bold text-slate-700 dark:text-slate-200 flex items-center gap-1.5 transition-colors">
                    🪄 Copiloto de Criação IA (Gemini)
                </label>
                <p className="text-xs text-slate-500 dark:text-slate-400 transition-colors">
                    Digite sua ideia (ex: "Crie uma questão de Cálculo 1 sobre limites fundamentais") e deixe a IA preencher o formulário para você.
                </p>
                <textarea
                    className="w-full p-3 border border-slate-200 dark:border-slate-700/60 rounded-xl text-sm bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 dark:focus:border-indigo-400 outline-none transition-all duration-200"
                    placeholder="Descreva a questão que deseja criar..."
                    value={promptIA}
                    onChange={(e) => setPromptIA(e.target.value)}
                    rows="2"
                    disabled={gerandoIA}
                />
                <div className="flex flex-col sm:flex-row gap-2">
                    <button
                        type="button"
                        onClick={handleGerarEsbocoIA}
                        className="flex-1 bg-violet-600 hover:bg-violet-700 text-white text-xs font-bold py-2.5 px-4 rounded-xl shadow-xs transition-all duration-200 disabled:opacity-50 cursor-pointer"
                        disabled={gerandoIA}
                    >
                        {gerandoIA ? "Gerando..." : "💡 Preencher Esboço"}
                    </button>
                    <button
                        type="button"
                        onClick={handleCriarTotalIA}
                        className="flex-1 bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-bold py-2.5 px-4 rounded-xl shadow-xs transition-all duration-200 disabled:opacity-50 cursor-pointer"
                        disabled={gerandoIA}
                    >
                        {gerandoIA ? "Publicando..." : "✨ Publicar Direto"}
                    </button>
                </div>
            </div>

            {/* Enunciado */}
            <div>
                <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-1.5">
                    Enunciado da Questão
                </label>
                <textarea
                    className="w-full p-3.5 border border-slate-200 dark:border-slate-700/60 rounded-xl bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 dark:focus:border-indigo-400 outline-none transition-all duration-200 min-h-[100px]"
                    placeholder="Digite o enunciado da questão (suporta fórmulas LaTeX com $...$)..."
                    value={novaQuestao.enunciado}
                    onChange={(e) => setNovaQuestao({ ...novaQuestao, enunciado: e.target.value })}
                    required
                />
            </div>

            {/* Matéria, Assunto e Dificuldade */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div>
                    <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-1.5">
                        Matéria
                    </label>
                    <input
                        className="w-full px-3.5 py-2.5 border border-slate-200 dark:border-slate-700/60 rounded-xl bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 dark:focus:border-indigo-400 outline-none text-sm transition-all duration-200"
                        placeholder="Ex: Java, Cálculo"
                        value={novaQuestao.materia}
                        onChange={(e) => setNovaQuestao({ ...novaQuestao, materia: e.target.value })}
                        required
                    />
                </div>

                <div>
                    <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-1.5">
                        Assunto
                    </label>
                    <input
                        className="w-full px-3.5 py-2.5 border border-slate-200 dark:border-slate-700/60 rounded-xl bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 dark:focus:border-indigo-400 outline-none text-sm transition-all duration-200"
                        placeholder="Ex: POO, Limites"
                        value={novaQuestao.assunto}
                        onChange={(e) => setNovaQuestao({ ...novaQuestao, assunto: e.target.value })}
                    />
                </div>

                <div>
                    <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-1.5">
                        Dificuldade
                    </label>
                    <select
                        className="w-full px-3.5 py-2.5 border border-slate-200 dark:border-slate-700/60 rounded-xl bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 dark:focus:border-indigo-400 outline-none text-sm transition-all duration-200 cursor-pointer"
                        value={novaQuestao.dificuldade}
                        onChange={(e) => setNovaQuestao({ ...novaQuestao, dificuldade: e.target.value })}
                    >
                        <option value="0">Fácil</option>
                        <option value="1">Médio</option>
                        <option value="2">Difícil</option>
                    </select>
                </div>
            </div>

            {/* Fonte */}
            <div>
                <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-1.5">
                    Fonte / Origem (Opcional)
                </label>
                <input
                    className="w-full px-3.5 py-2.5 border border-slate-200 dark:border-slate-700/60 rounded-xl bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 dark:focus:border-indigo-400 outline-none text-sm transition-all duration-200"
                    placeholder="Ex: ENEM 2023, Livro Stewart, Concurso BB"
                    value={novaQuestao.fonte}
                    onChange={(e) => setNovaQuestao({ ...novaQuestao, fonte: e.target.value })}
                />
            </div>

            {/* Trecho de Código */}
            <div>
                <div className="flex items-center justify-between mb-1.5">
                    <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider">
                        Trecho de Código (Opcional)
                    </label>
                    <select
                        className="px-2.5 py-1 text-xs border border-slate-200 dark:border-slate-700/60 rounded-lg bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 focus:ring-2 focus:ring-indigo-500/20 outline-none cursor-pointer"
                        value={novaQuestao.linguagemCodigo}
                        onChange={(e) => setNovaQuestao({ ...novaQuestao, linguagemCodigo: e.target.value })}
                    >
                        <option value="">Sem linguagem</option>
                        <option value="java">Java</option>
                        <option value="python">Python</option>
                        <option value="javascript">JavaScript</option>
                        <option value="cpp">C++</option>
                        <option value="csharp">C#</option>
                        <option value="sql">SQL</option>
                    </select>
                </div>
                <textarea
                    className="w-full p-3 font-mono text-sm border border-slate-200 dark:border-slate-700/60 rounded-xl bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100 placeholder:text-slate-400 dark:placeholder:text-slate-500 focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 dark:focus:border-indigo-400 outline-none transition-all duration-200"
                    placeholder="// Cole seu código aqui se a questão envolver programação..."
                    value={novaQuestao.trechoCodigo}
                    onChange={(e) => setNovaQuestao({ ...novaQuestao, trechoCodigo: e.target.value })}
                    rows="4"
                />
            </div>

            {/* Campo de Upload de Imagem */}
            <div>
                <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 uppercase tracking-wider mb-1.5">
                    Imagem da Questão (Opcional)
                </label>
                <input
                    type="file"
                    accept="image/*"
                    onChange={handleFileChange}
                    disabled={enviandoImagem}
                    className="w-full p-2 border border-slate-200 dark:border-slate-700/60 rounded-xl bg-white dark:bg-slate-900 text-slate-800 dark:text-slate-100 text-sm focus:ring-2 focus:ring-indigo-500/20 outline-none file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-semibold file:bg-indigo-50 dark:file:bg-indigo-950/40 file:text-indigo-600 dark:file:text-indigo-400 hover:file:bg-indigo-100 transition-colors cursor-pointer"
                />
                {enviandoImagem && <p className="text-xs text-indigo-500 dark:text-indigo-400 mt-1">Enviando imagem...</p>}

                {novaQuestao.imagemUrl && (
                    <div className="mt-2 relative inline-block">
                        <img
                            src={getMediaUrl(novaQuestao.imagemUrl)}
                            alt="Preview da imagem"
                            className="max-h-40 rounded-xl border border-slate-200 dark:border-slate-700/60 object-contain shadow-xs"
                        />
                        <button
                            type="button"
                            onClick={() => setNovaQuestao(prev => ({ ...prev, imagemUrl: "" }))}
                            className="absolute -top-2 -right-2 bg-red-600 hover:bg-red-700 text-white rounded-full p-1 text-xs w-6 h-6 flex items-center justify-center cursor-pointer font-bold shadow-sm"
                            title="Remover imagem"
                        >
                            ✕
                        </button>
                    </div>
                )}
            </div>

            <button
                type="submit"
                className="w-full py-3 rounded-xl font-semibold text-sm text-white bg-gradient-to-r from-indigo-500 to-violet-600 hover:from-indigo-400 hover:to-violet-500 hover:-translate-y-0.5 hover:shadow-lg hover:shadow-indigo-500/30 transition-all duration-200 cursor-pointer"
            >
                Adicionar Questão
            </button>
        </form>
    );
};

export default QuestaoForm;
